name: 'Test'

on:
  pull_request:
    branches:
      - '**'

jobs:
  Windows:
    runs-on: windows-2019
    environment: CI
    timeout-minutes: 10

    steps:
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Linting
        run: npm run lint

      - name: Run Tests (Chrome)
        run: node node_modules/gulp/bin/gulp.js test --testBrowserAlias=chrome

      - name: Run Tests (Firefox)
        run: node node_modules/gulp/bin/gulp.js test-run --testBrowserAlias=firefox
        if: ${{ always() }}

      - name: Run Tests (Edge)
        run: node node_modules/gulp/bin/gulp.js test-run --testBrowserAlias=edge
        if: ${{ always() }}

  macOS:
    runs-on: macos-latest
    environment: CI
    timeout-minutes: 10

    steps:
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: ESLint
        run: npm run lint

      - name: Run Tests (Chrome)
        run: node node_modules/gulp/bin/gulp.js test --testBrowserAlias=chrome

      - name: Run Tests (Firefox)
        run: node node_modules/gulp/bin/gulp.js test-run --testBrowserAlias=firefox
        if: ${{ always() }}

      - name: Run Tests (Safari)
        run: node node_modules/gulp/bin/gulp.js test-run --testBrowserAlias=safari
        if: ${{ always() }}
